export { default as Home } from "./Home";
export { default as Auth } from "./Auth";
export { default as Orders } from "./Orders";
export { default as Tables } from "./Tables";
export { default as Menu } from "./Menu";
export { default as Dashboard } from "./Dashboard";
export { default as Users } from "./Users";
export { default as Settings } from "./Settings";
export { default as Reports } from "./Reports";